// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mykiihodfokpskccbvfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15a2lpaG9kZm9rcHNrY2NidmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODM1OTQsImV4cCI6MjA2OTA1OTU5NH0.qOTSsoIaoSmuqLz_ZFXbA6qDTGnhz86HfEsOPBjOjRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});